//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHoaDon { get; set; }
        public double TienPhong { get; set; }
        public double TienDV { get; set; }
        public double TongTien { get; set; }
        public string HinhThucThanhToan { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public string GhiChu { get; set; }
        public int MaPhieuThuePhong { get; set; }
    
        public virtual Phieuthuephong Phieuthuephong { get; set; }
    }
}
