//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVu
    {
        public int MaSuDung { get; set; }
        public System.DateTime NgaySuDung { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public int MaDV { get; set; }
        public int MaChiTietPhieuThue { get; set; }
    
        public virtual ChiTietPhieuThue ChiTietPhieuThue { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
